INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(1,'test1','1','test1','test1@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(2,'test2','1','test2','test2@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(3,'test3','1','test3','test3@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(4,'test4','1','test4','test4@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(5,'test5','1','test5','test5@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(6,'test6','1','test6','test6@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(7,'test7','1','test7','test7@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(8,'test8','1','test8','test8@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(9,'test9','1','test9','test9@staroot.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES(10,'test10','1','test10','test10@staroot.com');

INSERT INTO BOARD (TITLE, CONTENTS, USER_ID, CREATE_DATE, MODIFY_DATE) VALUES('게시물1','게시물내용입니다<br>Hello ','1',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BOARD (TITLE, CONTENTS, USER_ID, CREATE_DATE, MODIFY_DATE) VALUES('게시물2','게시물내용입니다<br>Hello ','2',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BOARD (TITLE, CONTENTS, USER_ID, CREATE_DATE, MODIFY_DATE) VALUES('게시물3','게시물내용입니다<br>Hello ','3',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BOARD (TITLE, CONTENTS, USER_ID, CREATE_DATE, MODIFY_DATE) VALUES('게시물4','게시물내용입니다<br>Hello ','4',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BOARD (TITLE, CONTENTS, USER_ID, CREATE_DATE, MODIFY_DATE) VALUES('게시물5','게시물내용입니다<br>Hello ','5',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


